In [1]:
import pandas as pd
import numpy as np

# EDA Explorative Data Analysis

### Destatis-Daten laden
Die Daten werden aus Excel-File geladen. Für uns ist das Sheet Index_10-Steller interessant, welche Monatliche Preisindizes einzelner Lebensmittelprodukte zeigt.

In [2]:
destatis_df = pd.read_excel('data_raw/sonderauswertung-nahrungsmittel.xlsx', sheet_name='Index_10-Steller', skiprows=5)

### Daten ansehen
Daten werden betrachtet, Reihen ohne relevante Information gedropped und Spalten sinngemäß umbenannt.

In [3]:
destatis_df.head()

,Unnamed: 0,Unnamed: 1,Januar,Februar,März,April,Mai,Juni,Juli,August,...,September.4,Oktober.4,November.4,Dezember.4,Januar.5,Februar.5,März.5,April.5,Mai.5,Juni.5
0,CC13-0111101100,Reis,99.6,99.1,100.3,100.5,102.5,101.7,99.5,99.5,...,135.4,137.0,137.3,138.8,139.7,138.9,139.5,139.3,140.6,140.6
1,CC13-0111109100,Reiszubereitung,100.0,101.3,101.1,101.6,101.6,100.1,98.0,98.7,...,138.9,139.7,139.9,139.9,.,.,.,.,.,.
2,CC13-0111201100,Weizenmehl,100.9,100.8,100.0,102.1,102.6,101.9,98.8,98.9,...,159.4,153.6,150.8,153.1,152.9,153.6,153.2,148.8,151.6,152.1
3,CC13-0111203100,"Grieß, Roggenmehl oder Ähnliches",101.3,101.6,101.6,101.7,101.4,101.5,98.9,98.5,...,139.3,139.3,141.8,142.1,142.1,142.4,146.3,147,143.9,143.3
4,CC13-0111311100,Weißbrot,101.0,100.8,100.7,100.7,101.0,100.8,98.7,99.1,...,138.4,137.4,137.3,137.8,137.9,137.7,137.7,137.3,137.3,136.6

In [4]:
destatis_df

,Unnamed: 0,Unnamed: 1,Januar,Februar,März,April,Mai,Juni,Juli,August,...,September.4,Oktober.4,November.4,Dezember.4,Januar.5,Februar.5,März.5,April.5,Mai.5,Juni.5
0,CC13-0111101100,Reis,99.6,99.1,100.3,100.5,102.5,101.7,99.5,99.5,...,135.4,137.0,137.3,138.8,139.7,138.9,139.5,139.3,140.6,140.6
1,CC13-0111109100,Reiszubereitung,100.0,101.3,101.1,101.6,101.6,100.1,98.0,98.7,...,138.9,139.7,139.9,139.9,.,.,.,.,.,.
2,CC13-0111201100,Weizenmehl,100.9,100.8,100.0,102.1,102.6,101.9,98.8,98.9,...,159.4,153.6,150.8,153.1,152.9,153.6,153.2,148.8,151.6,152.1
3,CC13-0111203100,"Grieß, Roggenmehl oder Ähnliches",101.3,101.6,101.6,101.7,101.4,101.5,98.9,98.5,...,139.3,139.3,141.8,142.1,142.1,142.4,146.3,147,143.9,143.3
4,CC13-0111311100,Weißbrot,101.0,100.8,100.7,100.7,101.0,100.8,98.7,99.1,...,138.4,137.4,137.3,137.8,137.9,137.7,137.7,137.3,137.3,136.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,CC13-0122315100,Multivitaminsaft,100.9,100.3,99.7,100.2,102.1,101.7,99.4,99.6,...,143.0,142.3,143.7,143.7,144.1,146.8,148.5,150.9,150.2,149.7
167,CC13-0122320300,Gemüsesaft,100.3,99.7,100.3,100.5,100.7,100.7,99.8,99.6,...,140.1,140.1,141.5,141.5,.,.,.,.,.,.
168,______________,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,"© Statistisches Bundesamt (Destatis), 2025 | S...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,Ende der Tabelle.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
destatis_df.drop(index={168,169,170}, inplace=True)

In [6]:
destatis_df

,Unnamed: 0,Unnamed: 1,Januar,Februar,März,April,Mai,Juni,Juli,August,...,September.4,Oktober.4,November.4,Dezember.4,Januar.5,Februar.5,März.5,April.5,Mai.5,Juni.5
0,CC13-0111101100,Reis,99.6,99.1,100.3,100.5,102.5,101.7,99.5,99.5,...,135.4,137.0,137.3,138.8,139.7,138.9,139.5,139.3,140.6,140.6
1,CC13-0111109100,Reiszubereitung,100.0,101.3,101.1,101.6,101.6,100.1,98.0,98.7,...,138.9,139.7,139.9,139.9,.,.,.,.,.,.
2,CC13-0111201100,Weizenmehl,100.9,100.8,100.0,102.1,102.6,101.9,98.8,98.9,...,159.4,153.6,150.8,153.1,152.9,153.6,153.2,148.8,151.6,152.1
3,CC13-0111203100,"Grieß, Roggenmehl oder Ähnliches",101.3,101.6,101.6,101.7,101.4,101.5,98.9,98.5,...,139.3,139.3,141.8,142.1,142.1,142.4,146.3,147,143.9,143.3
4,CC13-0111311100,Weißbrot,101.0,100.8,100.7,100.7,101.0,100.8,98.7,99.1,...,138.4,137.4,137.3,137.8,137.9,137.7,137.7,137.3,137.3,136.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,CC13-0122230100,Energy-Drinks,101.7,101.6,102.6,101.7,101.6,101.7,97.8,99.0,...,112.4,113.1,113.6,113.6,.,.,.,.,.,.
164,CC13-0122311100,Apfelsaft oder ähnlicher Fruchtsaft,99.0,100.1,99.7,100.4,101.9,102.1,99.6,99.3,...,134.4,133.7,134.3,134.3,136.6,142.8,142.1,146.1,145,146.2
165,CC13-0122312200,Orangensaft oder ähnlicher Fruchtsaft,103.3,101.1,101.0,102.5,102.6,102.1,97.7,97.8,...,161.7,164.8,166.3,166.3,167.5,171.9,174.1,177.9,176.6,177.4
166,CC13-0122315100,Multivitaminsaft,100.9,100.3,99.7,100.2,102.1,101.7,99.4,99.6,...,143.0,142.3,143.7,143.7,144.1,146.8,148.5,150.9,150.2,149.7
167,CC13-0122320300,Gemüsesaft,100.3,99.7,100.3,100.5,100.7,100.7,99.8,99.6,...,140.1,140.1,141.5,141.5,.,.,.,.,.,.

In [7]:
destatis_df.rename(columns={'Unnamed: 0': 'COICOP-Index', 'Unnamed: 1':'Produkt'}, inplace=True)

### Fehlende Werte/NaN-Werte
Datensatz auf fehlende Werte analysieren. Dabei ergibt ein kurzer Blick in das Excel-Sheet, dass fehlende Werte nicht mit NaN gefüllt werden, sondern mit ".".
Wir ersetzen diese Werte durch np.nan und betrachten ihre Zusammenhänge.

#### Ergebnis
Bei 35 von 168 Produkten fehlen die Werte für das Jahr 2025.
Sonst treten keine NaN-Werte auf.

In [8]:
destatis_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 68 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   COICOP-Index  168 non-null    str
 1   Produkt       168 non-null    str
 2   Januar        168 non-null    float64
 3   Februar       168 non-null    float64
 4   März          168 non-null    float64
 5   April         168 non-null    float64
 6   Mai           168 non-null    float64
 7   Juni          168 non-null    float64
 8   Juli          168 non-null    float64
 9   August        168 non-null    float64
 10  September     168 non-null    float64
 11  Oktober       168 non-null    float64
 12  November      168 non-null    float64
 13  Dezember      168 non-null    float64
 14  Januar.1      168 non-null    float64
 15  Februar.1     168 non-null    float64
 16  März.1        168 non-null    float64
 17  April.1       168 non-null    float64
 18  Mai.1         168 non-null    float64
 19  Juni.1        168 non-null    float64
 20  Juli.1        168 non-null    float64
 21  August.1      168 non-null    float64
 22  September.1   168 non-null    float64
 23  Oktober.1     168 non-null    float64
 24  November.1    168 non-null    float64
 25  Dezember.1    168 non-null    float64
 26  Januar.2      168 non-null    float64
 27  Februar.2     168 non-null    float64
 28  März.2        168 non-null    float64
 29  April.2       168 non-null    float64
 30  Mai.2         168 non-null    float64
 31  Juni.2        168 non-null    float64
 32  Juli.2        168 non-null    float64
 33  August.2      168 non-null    float64
 34  September.2   168 non-null    float64
 35  Oktober.2     168 non-null    float64
 36  November.2    168 non-null    float64
 37  Dezember.2    168 non-null    float64
 38  Januar.3      168 non-null    float64
 39  Februar.3     168 non-null    float64
 40  März.3        168 non-null    float64
 41  April.3       168 non-null    float64
 42  Mai.3         168 non-null    float64
 43  Juni.3        168 non-null    float64
 44  Juli.3        168 non-null    float64
 45  August.3      168 non-null    float64
 46  September.3   168 non-null    float64
 47  Oktober.3     168 non-null    float64
 48  November.3    168 non-null    float64
 49  Dezember.3    168 non-null    float64
 50  Januar.4      168 non-null    float64
 51  Februar.4     168 non-null    float64
 52  März.4        168 non-null    float64
 53  April.4       168 non-null    float64
 54  Mai.4         168 non-null    float64
 55  Juni.4        168 non-null    float64
 56  Juli.4        168 non-null    float64
 57  August.4      168 non-null    float64
 58  September.4   168 non-null    float64
 59  Oktober.4     168 non-null    float64
 60  November.4    168 non-null    float64
 61  Dezember.4    168 non-null    float64
 62  Januar.5      168 non-null    object
 63  Februar.5     168 non-null    object
 64  März.5        168 non-null    object
 65  April.5       168 non-null    object
 66  Mai.5         168 non-null    object
 67  Juni.5        168 non-null    object
dtypes: float64(60), object(6), str(2)
memory usage: 89.4+ KB

In [9]:
(destatis_df == ".").sum()

COICOP-Index     0
Produkt          0
Januar           0
Februar          0
März             0
                ..
Februar.5       35
März.5          35
April.5         35
Mai.5           35
Juni.5          35
Length: 68, dtype: int64

In [10]:
destatis_df = destatis_df.replace(".", np.nan)

In [11]:
destatis_df.isnull().sum()

COICOP-Index     0
Produkt          0
Januar           0
Februar          0
März             0
                ..
Februar.5       35
März.5          35
April.5         35
Mai.5           35
Juni.5          35
Length: 68, dtype: int64

In [12]:
missing_per_month = {}

for col in destatis_df.columns:
    missing_per_month[col] = set(destatis_df.loc[destatis_df[col].isna(), "Produkt"])

In [14]:
missing_per_month["Januar.5"] == missing_per_month["Februar.5"] == missing_per_month["März.5"] == missing_per_month["April.5"] == missing_per_month["Mai.5"] == missing_per_month["Juni.5"]

True

##### Fehlende Werte in 2025
Bei 35/168 Produkten gibt es in den Monaten Januar bis Janu 2025 fehlende Werte. Bei den Produkten handelt es sich um:

In [15]:
missing_per_month["Januar.5"]

{'Backmischung für Kuchen',
 'Buttergemüse oder anderes tiefgefrorenes Gemüse',
 'Buttermilch oder anderes Milchgetränk',
 'Energy-Drinks',
 'Erbsenkonserve',
 'Feldsalat, Lauch, Sellerie oder Ähnliches',
 'Fertigdessert',
 'Fertigsuppe im Beutel oder Instantbrühe',
 'Fischmarinade',
 'Fleischwurst',
 'Früchtetee oder Kräutertee',
 'Gemüsesaft',
 'Gewürze',
 'Haferflocken',
 'Hefegebäck',
 'Hülsenfrüchte, Spargel, Radieschen oder Ähnliches',
 'Instantkaffee oder Ähnliches',
 'Kabeljau oder Lachs, frisch oder gekühlt',
 'Kasseler oder anderes Schweinefleisch',
 'Leberwurst oder Blutwurst',
 'Mayonnaise',
 'Nudeln',
 'Puddingpulver',
 'Reiszubereitung',
 'Roher Schinken, Schinkenspeck oder Bauchspeck',
 'Sahne',
 'Scholle, Forelle oder Karpfen, frisch oder gekühlt',
 'Schwarzer Tee oder grüner Tee',
 'Schweinekotelett oder Schweineschnitzel',
 'Senf',
 'Sojamilch, Reismilch o.Ä., ohne Kokosmilch',
 'Süße Mandeln, Kokosraspeln oder Ähnliches',
 'Tiefgefrorene Küchenkräuter',
 'Trockengemüse',
 'Vitamintabletten, Magnesiumtabletten o.Ä.'}

### Trendanalyse
Wir analysieren den Trend über alle Produkte hinweg, indem wir den Durchschnitt der Preisindizes im Januar 2024 mit dem Durchschnitt der Preisindizes im Juni 2025 vergleichen. Anschließend berechnen wir den prozentualen Trend für jedes Produkt und identifizieren die Top 10 Produkte mit dem stärksten Anstieg.

In [16]:
destatis_df["Januar"].mean()

np.float64(99.8077380952381)

In [17]:
destatis_df["Juni.5"].mean()

np.float64(137.16541353383457)

In [22]:
trend_ueber_alle_produkte = destatis_df["Juni.5"].mean() / destatis_df["Januar"].mean()
print(trend_ueber_alle_produkte )

1.3742963837428035

In [28]:
trend_df = destatis_df[["Produkt", "Januar", "Juni.5"]].copy()

In [29]:
trend_df[["Januar", "Juni.5"]] = trend_df[["Januar", "Juni.5"]].apply(pd.to_numeric, errors="coerce")

In [30]:
trend_df["trend"] = ((trend_df["Juni.5"] - trend_df["Januar"]) / trend_df["Januar"]) * 100

In [32]:
# ungültige Werte entfernen (NaN bei 2025)
trend_df = trend_df.replace([np.inf, -np.inf], np.nan).dropna(subset=["trend"])

In [33]:
top10 = trend_df.sort_values("trend", ascending=False).head(10)

In [34]:
top10

                                           Produkt  Januar  Juni.5      trend
12                                           Kekse   101.2   179.0  76.877470
103             Zwiebeln, Knoblauch oder Ähnliches    92.1   161.9  75.787188
69                                           Quark    97.1   170.4  75.489186
27                               Rinderhackfleisch    97.6   168.4  72.540984
165          Orangensaft oder ähnlicher Fruchtsaft   103.3   177.4  71.732817
14                        Knäckebrot oder Zwieback    99.4   170.5  71.529175
126  Riegel oder andere Erzeugnisse aus Schokolade    99.3   168.9  70.090634
158                     Kakaopulver oder Ähnliches    99.4   168.1  69.114688
111                             Sauerkrautkonserve    97.8   164.1  67.791411
64                              Kondensierte Milch    99.7   167.1  67.602808

#### Produkte mit hoher Preisstabilität
Wir identifizieren die Produkte mit der geringsten Preisänderung, indem wir die Produkte mit den niedrigsten absoluten Trendwerten auswählen. Diese Produkte zeigen eine hohe Preisstabilität über den betrachteten Zeitraum.

In [35]:
bottom10 = trend_df.sort_values("trend", ascending=True).head(10)
bottom10

                                     Produkt  Januar  Juni.5      trend
96               Kopfsalat oder Eisbergsalat   115.9    99.8 -13.891286
99                                   Tomaten   114.1    99.4 -12.883436
101                                   Gurken   100.3    99.4  -0.897308
87                               Weintrauben   111.6   112.1   0.448029
102           Kürbisse, Auberginen oder Mais    99.8   102.0   2.204409
56               Tiefgefrorene Meeresfrüchte   101.3   105.9   4.540967
123                                    Honig   101.2   111.4  10.079051
23   Getreideprodukt, vegetarisch oder vegan   102.3   112.7  10.166178
115    Gemüseprodukt, vegetarisch oder vegan   101.7   112.6  10.717797
131                                 Süßstoff   101.7   112.6  10.717797

In [36]:
stabilste10 = (
    trend_df.assign(abs_trend=trend_df["trend"].abs())
            .sort_values("abs_trend", ascending=True)
            .head(10)
            .drop(columns="abs_trend")
)
stabilste10

                                     Produkt  Januar  Juni.5      trend
87                               Weintrauben   111.6   112.1   0.448029
101                                   Gurken   100.3    99.4  -0.897308
102           Kürbisse, Auberginen oder Mais    99.8   102.0   2.204409
56               Tiefgefrorene Meeresfrüchte   101.3   105.9   4.540967
123                                    Honig   101.2   111.4  10.079051
23   Getreideprodukt, vegetarisch oder vegan   102.3   112.7  10.166178
131                                 Süßstoff   101.7   112.6  10.717797
115    Gemüseprodukt, vegetarisch oder vegan   101.7   112.6  10.717797
99                                   Tomaten   114.1    99.4 -12.883436
96               Kopfsalat oder Eisbergsalat   115.9    99.8 -13.891286