In [1]:
import pandas as pd

In [2]:
# Load the dataset
destatis_df = pd.read_csv('data_processed/features_destatis.csv')

In [3]:
destatis_df.loc[[destatis_df["Preisindex"].idxmax()]]

,COICOP-Index,Produkt,Monat,Preisindex,Monat_Nr,lag_1,lag_2,lag_3,rolling_mean_3,rolling_mean_6,Datum,Risikogruppe,preisanstieg_pct
3377,CC13-0117134100,Gurken,März.3,213.1,39.0,198.9,148.6,143.2,163.566667,148.633333,2023-03-01,stabil,-0.897308

In [6]:
mean_price_index = destatis_df["Preisindex"].mean(skipna=True)
print(f"Mean Preisindex: {mean_price_index}")

Mean Preisindex: 117.50015390186492

In [8]:
destatis_df.groupby("Produkt")["Preisindex"].mean()

Produkt
Ananaskonserve, Erdbeerkonserve oder Ähnliches    133.898507
Antipasti auf Gemüsebasis, ohne Oliven            108.856716
Apfelmus oder andere Kernobstkonserve             119.302985
Apfelsaft oder ähnlicher Fruchtsaft               116.238806
Backmischung für Kuchen                           110.119672
                                                     ...
Zitrusfrüchte                                     105.061194
Zubereitetes Hackfleisch                          119.926866
Zucker                                            134.450746
Zwiebeln, Knoblauch oder Ähnliches                123.761194
Äpfel                                             106.268657
Name: Preisindex, Length: 168, dtype: float64

In [10]:
destatis_df.groupby("Produkt")["Preisindex"].std()

Produkt
Ananaskonserve, Erdbeerkonserve oder Ähnliches    23.266529
Antipasti auf Gemüsebasis, ohne Oliven             9.476450
Apfelmus oder andere Kernobstkonserve             17.749409
Apfelsaft oder ähnlicher Fruchtsaft               15.955003
Backmischung für Kuchen                           16.980674
                                                    ...
Zitrusfrüchte                                     10.535912
Zubereitetes Hackfleisch                          17.610117
Zucker                                            34.949402
Zwiebeln, Knoblauch oder Ähnliches                28.518564
Äpfel                                              7.212368
Name: Preisindex, Length: 168, dtype: float64

In [11]:
destatis_df.groupby("Produkt")["Preisindex"].median()

Produkt
Ananaskonserve, Erdbeerkonserve oder Ähnliches    145.1
Antipasti auf Gemüsebasis, ohne Oliven            110.5
Apfelmus oder andere Kernobstkonserve             113.8
Apfelsaft oder ähnlicher Fruchtsaft               108.6
Backmischung für Kuchen                           102.5
                                                  ...
Zitrusfrüchte                                     105.3
Zubereitetes Hackfleisch                          128.6
Zucker                                            121.0
Zwiebeln, Knoblauch oder Ähnliches                123.1
Äpfel                                             106.9
Name: Preisindex, Length: 168, dtype: float64

In [12]:
cpi_df = pd.read_csv('data_raw/cpi_de.csv')

In [13]:
cpi_df

         Datum    CPI
0   2020-01-01   99.1
1   2020-02-01   99.4
2   2020-03-01   99.5
3   2020-04-01   98.5
4   2020-05-01   98.7
..         ...    ...
61  2025-02-01  120.8
62  2025-03-01  121.2
63  2025-04-01  121.7
64  2025-05-01  121.8
65  2025-06-01  121.8

[66 rows x 2 columns]

In [14]:
cpi_df["Datum"] = pd.to_datetime(cpi_df["Datum"])
cpi_df = cpi_df.sort_values("Datum")

cpi_df["MoM"] = cpi_df["CPI"].pct_change() * 100  # in Prozent
print(cpi_df[["Datum", "CPI", "MoM"]])

        Datum    CPI       MoM
0  2020-01-01   99.1       NaN
1  2020-02-01   99.4  0.302725
2  2020-03-01   99.5  0.100604
3  2020-04-01   98.5 -1.005025
4  2020-05-01   98.7  0.203046
..        ...    ...       ...
61 2025-02-01  120.8  0.415628
62 2025-03-01  121.2  0.331126
63 2025-04-01  121.7  0.412541
64 2025-05-01  121.8  0.082169
65 2025-06-01  121.8  0.000000

[66 rows x 3 columns]

In [15]:

cpi_df

        Datum    CPI       MoM
0  2020-01-01   99.1       NaN
1  2020-02-01   99.4  0.302725
2  2020-03-01   99.5  0.100604
3  2020-04-01   98.5 -1.005025
4  2020-05-01   98.7  0.203046
..        ...    ...       ...
61 2025-02-01  120.8  0.415628
62 2025-03-01  121.2  0.331126
63 2025-04-01  121.7  0.412541
64 2025-05-01  121.8  0.082169
65 2025-06-01  121.8  0.000000

[66 rows x 3 columns]

In [16]:
cpi_df["Datum"] = pd.to_datetime(cpi_df["Datum"])
cpi_df = cpi_df.sort_values("Datum").copy()

cpi_df["YoY_%"] = (cpi_df["CPI"] / cpi_df["CPI"].shift(12) - 1) * 100
cpi_df["MoM_%"] = (cpi_df["CPI"] / cpi_df["CPI"].shift(1)  - 1) * 100

print(cpi_df[["Datum", "CPI", "MoM_%", "YoY_%"]].round(3))

        Datum    CPI  MoM_%  YoY_%
0  2020-01-01   99.1    NaN    NaN
1  2020-02-01   99.4  0.303    NaN
2  2020-03-01   99.5  0.101    NaN
3  2020-04-01   98.5 -1.005    NaN
4  2020-05-01   98.7  0.203    NaN
..        ...    ...    ...    ...
61 2025-02-01  120.8  0.416  2.286
62 2025-03-01  121.2  0.331  2.192
63 2025-04-01  121.7  0.413  2.097
64 2025-05-01  121.8  0.082  2.096
65 2025-06-01  121.8  0.000  2.010

[66 rows x 4 columns]

/var/folders/3x/nffd18314rsbfjzd3b_p969r0000gn/T/ipykernel_86490/818851814.py:7: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  print(cpi_df[["Datum", "CPI", "MoM_%", "YoY_%"]].round(3))

In [17]:
cpi_df

        Datum    CPI       MoM     YoY_%     MoM_%
0  2020-01-01   99.1       NaN       NaN       NaN
1  2020-02-01   99.4  0.302725       NaN  0.302725
2  2020-03-01   99.5  0.100604       NaN  0.100604
3  2020-04-01   98.5 -1.005025       NaN -1.005025
4  2020-05-01   98.7  0.203046       NaN  0.203046
..        ...    ...       ...       ...       ...
61 2025-02-01  120.8  0.415628  2.286198  0.415628
62 2025-03-01  121.2  0.331126  2.192243  0.331126
63 2025-04-01  121.7  0.412541  2.097315  0.412541
64 2025-05-01  121.8  0.082169  2.095557  0.082169
65 2025-06-01  121.8  0.000000  2.010050  0.000000

[66 rows x 5 columns]